# Neo4j DB Configuration

development:
  type: http
  url: http://localhost:7474

test:
  type: http
  url: http://localhost:7474

production:
  type: http
  url: http://neo4j:neo4jadmin@localhost:7687